#database
datasource:
  params:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/contur_estet?useSSL=false
    username: root
    password: root

#spring
spring:
  datasource:
    separator: ^;
    initialization-mode: always
